package com.btjf.distributed.core.spi.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DistributedTransactionDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    public DistributedTransactionDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTransIDIsNull() {
            addCriterion("transID is null");
            return (Criteria) this;
        }

        public Criteria andTransIDIsNotNull() {
            addCriterion("transID is not null");
            return (Criteria) this;
        }

        public Criteria andTransIDEqualTo(String value) {
            addCriterion("transID =", value, "transID");
            return (Criteria) this;
        }

        public Criteria andTransIDNotEqualTo(String value) {
            addCriterion("transID <>", value, "transID");
            return (Criteria) this;
        }

        public Criteria andTransIDGreaterThan(String value) {
            addCriterion("transID >", value, "transID");
            return (Criteria) this;
        }

        public Criteria andTransIDGreaterThanOrEqualTo(String value) {
            addCriterion("transID >=", value, "transID");
            return (Criteria) this;
        }

        public Criteria andTransIDLessThan(String value) {
            addCriterion("transID <", value, "transID");
            return (Criteria) this;
        }

        public Criteria andTransIDLessThanOrEqualTo(String value) {
            addCriterion("transID <=", value, "transID");
            return (Criteria) this;
        }

        public Criteria andTransIDLike(String value) {
            addCriterion("transID like", value, "transID");
            return (Criteria) this;
        }

        public Criteria andTransIDNotLike(String value) {
            addCriterion("transID not like", value, "transID");
            return (Criteria) this;
        }

        public Criteria andTransIDIn(List<String> values) {
            addCriterion("transID in", values, "transID");
            return (Criteria) this;
        }

        public Criteria andTransIDNotIn(List<String> values) {
            addCriterion("transID not in", values, "transID");
            return (Criteria) this;
        }

        public Criteria andTransIDBetween(String value1, String value2) {
            addCriterion("transID between", value1, value2, "transID");
            return (Criteria) this;
        }

        public Criteria andTransIDNotBetween(String value1, String value2) {
            addCriterion("transID not between", value1, value2, "transID");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRoleIsNull() {
            addCriterion("role is null");
            return (Criteria) this;
        }

        public Criteria andRoleIsNotNull() {
            addCriterion("role is not null");
            return (Criteria) this;
        }

        public Criteria andRoleEqualTo(Integer value) {
            addCriterion("role =", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotEqualTo(Integer value) {
            addCriterion("role <>", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleGreaterThan(Integer value) {
            addCriterion("role >", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleGreaterThanOrEqualTo(Integer value) {
            addCriterion("role >=", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLessThan(Integer value) {
            addCriterion("role <", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLessThanOrEqualTo(Integer value) {
            addCriterion("role <=", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleIn(List<Integer> values) {
            addCriterion("role in", values, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotIn(List<Integer> values) {
            addCriterion("role not in", values, "role");
            return (Criteria) this;
        }

        public Criteria andRoleBetween(Integer value1, Integer value2) {
            addCriterion("role between", value1, value2, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotBetween(Integer value1, Integer value2) {
            addCriterion("role not between", value1, value2, "role");
            return (Criteria) this;
        }

        public Criteria andRetriedCountIsNull() {
            addCriterion("retriedCount is null");
            return (Criteria) this;
        }

        public Criteria andRetriedCountIsNotNull() {
            addCriterion("retriedCount is not null");
            return (Criteria) this;
        }

        public Criteria andRetriedCountEqualTo(Integer value) {
            addCriterion("retriedCount =", value, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andRetriedCountNotEqualTo(Integer value) {
            addCriterion("retriedCount <>", value, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andRetriedCountGreaterThan(Integer value) {
            addCriterion("retriedCount >", value, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andRetriedCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("retriedCount >=", value, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andRetriedCountLessThan(Integer value) {
            addCriterion("retriedCount <", value, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andRetriedCountLessThanOrEqualTo(Integer value) {
            addCriterion("retriedCount <=", value, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andRetriedCountIn(List<Integer> values) {
            addCriterion("retriedCount in", values, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andRetriedCountNotIn(List<Integer> values) {
            addCriterion("retriedCount not in", values, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andRetriedCountBetween(Integer value1, Integer value2) {
            addCriterion("retriedCount between", value1, value2, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andRetriedCountNotBetween(Integer value1, Integer value2) {
            addCriterion("retriedCount not between", value1, value2, "retriedCount");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("createTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeIsNull() {
            addCriterion("lastTime is null");
            return (Criteria) this;
        }

        public Criteria andLastTimeIsNotNull() {
            addCriterion("lastTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastTimeEqualTo(Date value) {
            addCriterion("lastTime =", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeNotEqualTo(Date value) {
            addCriterion("lastTime <>", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeGreaterThan(Date value) {
            addCriterion("lastTime >", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("lastTime >=", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeLessThan(Date value) {
            addCriterion("lastTime <", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeLessThanOrEqualTo(Date value) {
            addCriterion("lastTime <=", value, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeIn(List<Date> values) {
            addCriterion("lastTime in", values, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeNotIn(List<Date> values) {
            addCriterion("lastTime not in", values, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeBetween(Date value1, Date value2) {
            addCriterion("lastTime between", value1, value2, "lastTime");
            return (Criteria) this;
        }

        public Criteria andLastTimeNotBetween(Date value1, Date value2) {
            addCriterion("lastTime not between", value1, value2, "lastTime");
            return (Criteria) this;
        }

        public Criteria andTargetClassIsNull() {
            addCriterion("targetClass is null");
            return (Criteria) this;
        }

        public Criteria andTargetClassIsNotNull() {
            addCriterion("targetClass is not null");
            return (Criteria) this;
        }

        public Criteria andTargetClassEqualTo(String value) {
            addCriterion("targetClass =", value, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassNotEqualTo(String value) {
            addCriterion("targetClass <>", value, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassGreaterThan(String value) {
            addCriterion("targetClass >", value, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassGreaterThanOrEqualTo(String value) {
            addCriterion("targetClass >=", value, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassLessThan(String value) {
            addCriterion("targetClass <", value, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassLessThanOrEqualTo(String value) {
            addCriterion("targetClass <=", value, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassLike(String value) {
            addCriterion("targetClass like", value, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassNotLike(String value) {
            addCriterion("targetClass not like", value, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassIn(List<String> values) {
            addCriterion("targetClass in", values, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassNotIn(List<String> values) {
            addCriterion("targetClass not in", values, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassBetween(String value1, String value2) {
            addCriterion("targetClass between", value1, value2, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetClassNotBetween(String value1, String value2) {
            addCriterion("targetClass not between", value1, value2, "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetMethodIsNull() {
            addCriterion("targetMethod is null");
            return (Criteria) this;
        }

        public Criteria andTargetMethodIsNotNull() {
            addCriterion("targetMethod is not null");
            return (Criteria) this;
        }

        public Criteria andTargetMethodEqualTo(String value) {
            addCriterion("targetMethod =", value, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodNotEqualTo(String value) {
            addCriterion("targetMethod <>", value, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodGreaterThan(String value) {
            addCriterion("targetMethod >", value, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodGreaterThanOrEqualTo(String value) {
            addCriterion("targetMethod >=", value, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodLessThan(String value) {
            addCriterion("targetMethod <", value, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodLessThanOrEqualTo(String value) {
            addCriterion("targetMethod <=", value, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodLike(String value) {
            addCriterion("targetMethod like", value, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodNotLike(String value) {
            addCriterion("targetMethod not like", value, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodIn(List<String> values) {
            addCriterion("targetMethod in", values, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodNotIn(List<String> values) {
            addCriterion("targetMethod not in", values, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodBetween(String value1, String value2) {
            addCriterion("targetMethod between", value1, value2, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andTargetMethodNotBetween(String value1, String value2) {
            addCriterion("targetMethod not between", value1, value2, "targetMethod");
            return (Criteria) this;
        }

        public Criteria andErrorMsgIsNull() {
            addCriterion("errorMsg is null");
            return (Criteria) this;
        }

        public Criteria andErrorMsgIsNotNull() {
            addCriterion("errorMsg is not null");
            return (Criteria) this;
        }

        public Criteria andErrorMsgEqualTo(String value) {
            addCriterion("errorMsg =", value, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgNotEqualTo(String value) {
            addCriterion("errorMsg <>", value, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgGreaterThan(String value) {
            addCriterion("errorMsg >", value, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgGreaterThanOrEqualTo(String value) {
            addCriterion("errorMsg >=", value, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgLessThan(String value) {
            addCriterion("errorMsg <", value, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgLessThanOrEqualTo(String value) {
            addCriterion("errorMsg <=", value, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgLike(String value) {
            addCriterion("errorMsg like", value, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgNotLike(String value) {
            addCriterion("errorMsg not like", value, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgIn(List<String> values) {
            addCriterion("errorMsg in", values, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgNotIn(List<String> values) {
            addCriterion("errorMsg not in", values, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgBetween(String value1, String value2) {
            addCriterion("errorMsg between", value1, value2, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgNotBetween(String value1, String value2) {
            addCriterion("errorMsg not between", value1, value2, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andApplicationNameIsNull() {
            addCriterion("applicationName is null");
            return (Criteria) this;
        }

        public Criteria andApplicationNameIsNotNull() {
            addCriterion("applicationName is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationNameEqualTo(String value) {
            addCriterion("applicationName =", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameNotEqualTo(String value) {
            addCriterion("applicationName <>", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameGreaterThan(String value) {
            addCriterion("applicationName >", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameGreaterThanOrEqualTo(String value) {
            addCriterion("applicationName >=", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameLessThan(String value) {
            addCriterion("applicationName <", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameLessThanOrEqualTo(String value) {
            addCriterion("applicationName <=", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameLike(String value) {
            addCriterion("applicationName like", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameNotLike(String value) {
            addCriterion("applicationName not like", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameIn(List<String> values) {
            addCriterion("applicationName in", values, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameNotIn(List<String> values) {
            addCriterion("applicationName not in", values, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameBetween(String value1, String value2) {
            addCriterion("applicationName between", value1, value2, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameNotBetween(String value1, String value2) {
            addCriterion("applicationName not between", value1, value2, "applicationName");
            return (Criteria) this;
        }

        public Criteria andTransIDLikeInsensitive(String value) {
            addCriterion("upper(transID) like", value.toUpperCase(), "transID");
            return (Criteria) this;
        }

        public Criteria andTargetClassLikeInsensitive(String value) {
            addCriterion("upper(targetClass) like", value.toUpperCase(), "targetClass");
            return (Criteria) this;
        }

        public Criteria andTargetMethodLikeInsensitive(String value) {
            addCriterion("upper(targetMethod) like", value.toUpperCase(), "targetMethod");
            return (Criteria) this;
        }

        public Criteria andErrorMsgLikeInsensitive(String value) {
            addCriterion("upper(errorMsg) like", value.toUpperCase(), "errorMsg");
            return (Criteria) this;
        }

        public Criteria andApplicationNameLikeInsensitive(String value) {
            addCriterion("upper(applicationName) like", value.toUpperCase(), "applicationName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}