package com.btjf.distributed.core.spi.model;

import java.io.Serializable;
import java.util.Date;

public class DistributedTransactionData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_distributed_transaction.transID
     *
     * @mbg.generated
     */
    private String transID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_distributed_transaction.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_distributed_transaction.role
     *
     * @mbg.generated
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_distributed_transaction.retriedCount
     *
     * @mbg.generated
     */
    private Integer retriedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_distributed_transaction.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_distributed_transaction.lastTime
     *
     * @mbg.generated
     */
    private Date lastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_distributed_transaction.targetClass
     *
     * @mbg.generated
     */
    private String targetClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_distributed_transaction.targetMethod
     *
     * @mbg.generated
     */
    private String targetMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_distributed_transaction.errorMsg
     *
     * @mbg.generated
     */
    private String errorMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_distributed_transaction.applicationName
     *
     * @mbg.generated
     */
    private String applicationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_distributed_transaction.transID
     *
     * @return the value of s_distributed_transaction.transID
     *
     * @mbg.generated
     */
    public String getTransID() {
        return transID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_distributed_transaction.transID
     *
     * @param transID the value for s_distributed_transaction.transID
     *
     * @mbg.generated
     */
    public void setTransID(String transID) {
        this.transID = transID == null ? null : transID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_distributed_transaction.status
     *
     * @return the value of s_distributed_transaction.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_distributed_transaction.status
     *
     * @param status the value for s_distributed_transaction.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_distributed_transaction.role
     *
     * @return the value of s_distributed_transaction.role
     *
     * @mbg.generated
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_distributed_transaction.role
     *
     * @param role the value for s_distributed_transaction.role
     *
     * @mbg.generated
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_distributed_transaction.retriedCount
     *
     * @return the value of s_distributed_transaction.retriedCount
     *
     * @mbg.generated
     */
    public Integer getRetriedCount() {
        return retriedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_distributed_transaction.retriedCount
     *
     * @param retriedCount the value for s_distributed_transaction.retriedCount
     *
     * @mbg.generated
     */
    public void setRetriedCount(Integer retriedCount) {
        this.retriedCount = retriedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_distributed_transaction.createTime
     *
     * @return the value of s_distributed_transaction.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_distributed_transaction.createTime
     *
     * @param createTime the value for s_distributed_transaction.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_distributed_transaction.lastTime
     *
     * @return the value of s_distributed_transaction.lastTime
     *
     * @mbg.generated
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_distributed_transaction.lastTime
     *
     * @param lastTime the value for s_distributed_transaction.lastTime
     *
     * @mbg.generated
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_distributed_transaction.targetClass
     *
     * @return the value of s_distributed_transaction.targetClass
     *
     * @mbg.generated
     */
    public String getTargetClass() {
        return targetClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_distributed_transaction.targetClass
     *
     * @param targetClass the value for s_distributed_transaction.targetClass
     *
     * @mbg.generated
     */
    public void setTargetClass(String targetClass) {
        this.targetClass = targetClass == null ? null : targetClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_distributed_transaction.targetMethod
     *
     * @return the value of s_distributed_transaction.targetMethod
     *
     * @mbg.generated
     */
    public String getTargetMethod() {
        return targetMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_distributed_transaction.targetMethod
     *
     * @param targetMethod the value for s_distributed_transaction.targetMethod
     *
     * @mbg.generated
     */
    public void setTargetMethod(String targetMethod) {
        this.targetMethod = targetMethod == null ? null : targetMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_distributed_transaction.errorMsg
     *
     * @return the value of s_distributed_transaction.errorMsg
     *
     * @mbg.generated
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_distributed_transaction.errorMsg
     *
     * @param errorMsg the value for s_distributed_transaction.errorMsg
     *
     * @mbg.generated
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_distributed_transaction.applicationName
     *
     * @return the value of s_distributed_transaction.applicationName
     *
     * @mbg.generated
     */
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_distributed_transaction.applicationName
     *
     * @param applicationName the value for s_distributed_transaction.applicationName
     *
     * @mbg.generated
     */
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName == null ? null : applicationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DistributedTransactionData other = (DistributedTransactionData) that;
        return (this.getTransID() == null ? other.getTransID() == null : this.getTransID().equals(other.getTransID()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getRole() == null ? other.getRole() == null : this.getRole().equals(other.getRole()))
            && (this.getRetriedCount() == null ? other.getRetriedCount() == null : this.getRetriedCount().equals(other.getRetriedCount()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getLastTime() == null ? other.getLastTime() == null : this.getLastTime().equals(other.getLastTime()))
            && (this.getTargetClass() == null ? other.getTargetClass() == null : this.getTargetClass().equals(other.getTargetClass()))
            && (this.getTargetMethod() == null ? other.getTargetMethod() == null : this.getTargetMethod().equals(other.getTargetMethod()))
            && (this.getErrorMsg() == null ? other.getErrorMsg() == null : this.getErrorMsg().equals(other.getErrorMsg()))
            && (this.getApplicationName() == null ? other.getApplicationName() == null : this.getApplicationName().equals(other.getApplicationName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_distributed_transaction
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTransID() == null) ? 0 : getTransID().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getRole() == null) ? 0 : getRole().hashCode());
        result = prime * result + ((getRetriedCount() == null) ? 0 : getRetriedCount().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getLastTime() == null) ? 0 : getLastTime().hashCode());
        result = prime * result + ((getTargetClass() == null) ? 0 : getTargetClass().hashCode());
        result = prime * result + ((getTargetMethod() == null) ? 0 : getTargetMethod().hashCode());
        result = prime * result + ((getErrorMsg() == null) ? 0 : getErrorMsg().hashCode());
        result = prime * result + ((getApplicationName() == null) ? 0 : getApplicationName().hashCode());
        return result;
    }
}