server:
  port: 9010

logging:
  file: ogs/application.log
  level:
    com:
      btjf: DEBUG

spring:
  application:
    name: distributed-transaction
  #json日期格式配置
  jackson: 
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    timeZone: GMT+8

#  profiles:
#    active: dev
  aop:
    proxy-target-class: true

#分布式事物日志存储方式
distributed:
  transaction:
    repository:
      type: redis
#序列化方式
serializer:
  type: kryo
#事物补偿时，MQ重发次数
retried:
  count: 3

coordinator:
  queue:
    max: 10